apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-example-com
spec:
  dnsNames:
  - '*.example.com'
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretName: wildcard-example-com-tls
